/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js during installation. It is kept here so
// TypeScript understands the Next.js runtime before the first dev run.
